name: Lint

on:
  pull_request:
    paths:
    - '/**'
    - '.github/workflows/ci-helm-workflow.yml'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Validate schema
        id: kubeval
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm plugin install https://github.com/instrumenta/helm-kubeval
          helm dependency build
          helm lint
          helm kubeval .``